apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "talos-cloud-controller-manager.fullname" . }}
  labels:
    {{- include "talos-cloud-controller-manager.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  ccm-config.yaml: |
    global:
  {{- if .Values.features.approveNodeCSR }}
      approveNodeCSR: true
  {{- end }}
  {{- with .Values.transformations }}
    transformations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
