{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "talos-cloud-controller-manager.serviceAccountName" . }}
  labels:
    {{- include "talos-cloud-controller-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ include "talos-cloud-controller-manager.serviceAccountName" . }}-talos-secrets
  labels:
    {{- include "talos-cloud-controller-manager.labels" . | nindent 4 }}
spec:
  roles:
    - os:reader
